# Generated by Django 5.1.5 on 2025-07-01 20:37

from django.db import migrations

def crear_categorias_padrao(apps, schema_editor):
    # Obtenemos el modelo Categoria del registro de aplicaciones
    Categoria = apps.get_model('gestor_gastos', 'Categoria')

    # Definimos las categorías que queremos crear por defecto
    categorias_iniciales = [
        {'nombre': 'Gasto Hormiga'},
        {'nombre': 'Transporte'},
        {'nombre': 'Cuentas Fijas Mensuales'},
        {'nombre': 'Salud'},
        {'nombre': 'Otros Gastos'},
    ]

    # Recorremos la lista y creamos cada categoría si no existe ya
    for categoria_data in categorias_iniciales:
        Categoria.objects.get_or_create(**categoria_data) # get_or_create evita duplicados

class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0001_initial'), # Asegúrate que '0001_initial' sea el nombre de tu migración inicial
                                                # o la migración que creó el modelo Categoria
    ]

    operations = [
        migrations.RunPython(crear_categorias_padrao), # Ejecuta la función de creación de categorías
    ]